feat/adding client
aalmds/MESU pull request #6
Opened 2022-08-20 21:35 UTC by mluisass

Adding Kora's client.

2022-08-21 15:15 UTC, acrucha approved these changes

2022-08-21 17:30 UTC, vcnovaes requested changes

2022-08-21 17:30 UTC, vcnovaes commented on module2/src/index.js
> +    '3': 'Alto - cerca de 38 cm',
Eu achava que a posição do nosso prototipo seria relativa ao local que ele fosse colocado

2022-08-21 17:30 UTC, vcnovaes commented on module2/src/index.js
> +    }
Tratar o caso de mais de um sensor com problema. 
Pois se tiver erro, teremos 
Erro no sensor 1 sensor 2 sensor 3. 
Talvez fosse melhor fazer 
Erro no sensor 1, 2, 3.

2022-08-21 17:30 UTC, vcnovaes commented on module2/src/index.js
> +    statusElement.innerText = 'Ok'
mudar para OK

2022-08-21 17:30 UTC, vcnovaes commented on module2/src/index.html
> +            <button class="button button1" onclick="showTable()">History</button>
Nome do botão em inglês

2022-08-21 17:30 UTC, vcnovaes commented on module2/src/index.html
> +                <th class="tbHeader">Dado</th>
Dado -> Nível fica melhor?

2022-08-21 17:30 UTC, vcnovaes commented on module2/src/equipe.html
> +              <small> <big>Edna Barros</big> <i> - Orientadora</i></small>
Apenas orientadora é muito aberto, teria como adicionar mais informações a respeito dela?

2022-08-21 17:30 UTC, vcnovaes commented on module2/src/index.html
> +              <a class="nav-link" href="./index.html">Mapeamento dos sensores</a>
Mapeamento dos sensores é um nome  muito grande para nav bar, talvez só Mapa seria melhor e informaria a mesma coisa

2022-08-21 17:30 UTC, vcnovaes commented on module2/src/equipe.html
> +              <small><big>Vinícius Novaes</big> <i> - Graduanda em Engenharia da Computação</i></small>
Graduando* e não graduanda , o mesmo vale para Tales

2022-08-21 17:30 UTC, vcnovaes commented on module2/src/equipe.html
> +              <p><br><img src = "../img/Vitoria.jpeg" width="100" > </img>
Seria interessante informar de que universidade somos

2022-08-21 17:34 UTC, aalmds commented on module2/src/index.js
> +    '3': 'Alto - cerca de 38 cm',
Isso seria somente nos próximos passos, atualmente a gente mapeia para o protótipo estando em um poste ou na parede de algum estacionamento, a uma altura fixa do chão.

2022-08-21 17:36 UTC, becca-ls requested changes

2022-08-21 17:36 UTC, becca-ls commented on module2/src/index.js
> +  const levelMap = {
"Nível de água: seco" não me parece muito correto, eu acharia melhor para substituir por algo como , por exemplo: Nível de água: 
      Muito baixo
      Baixo
      Médio
      Alto
      Muito alto
      Erro de medição

2022-08-21 17:36 UTC, becca-ls commented on module2/src/index.js
> +    '4': 'Muito alto -  cerca de 48 cm',
Sobre as medidas informadas, não acho muito interessante informar dessa maneira não. Além de serem valores bem quebrados é muito arbitrário, pois depende da altura que a torre é instalada, depende se é um ponto alto ou baixo da rua etc. Como essas medidas foram calculadas? Não vi um padrão de distância entre os sensores.

2022-08-21 17:36 UTC, becca-ls commented on module2/src/equipe.html
> +              <small> <big>Edna Barros</big> <i> - Orientadora</i></small>
A versão original tinha "Profª Edna..." o que acredito ser melhor, pois ficou sem uma boa referência para a professora. Talvez seja até melhor "Professora" mesmo do que abreviado, mas tem que ter.

2022-08-21 17:36 UTC, becca-ls commented on module2/src/equipe.html
> +              <small><big>Vinícius Novaes</big> <i> - Graduanda em Engenharia da Computação</i></small>
Vinícius e Tales estão com "graduanda" no feminino.

2022-08-21 17:36 UTC, becca-ls commented on module2/src/index.html
> +            <button class="button button1" onclick="showTable()">History</button>
É muito estranho o botão em inglês e todo o resto alinhado em português. Além disso, não me parece legal o botão em baixo e a tabela aparecendo lá do lado do mapa, não acho muito intuitivo. Sugiro mudar o local do botão ou da tabela.

2022-08-21 17:36 UTC, becca-ls commented on module2/src/index.html
> +<!doctype html>
Como sugestão, seria interessante adicionar a logo do cin. Poderia ficar no canto superior direito, na barra. Até me lembrei quando estava criando este arquivo, mas não acertei. Caso alguém consiga, tem que lembrar de colocar na página Equipe tb.

2022-08-21 17:41 UTC, aalmds commented on module2/src/index.html
> +                <th class="tbHeader">Dado</th>
Sim!

2022-08-21 17:41 UTC, aalmds commented on module2/src/equipe.html
> +              <small> <big>Edna Barros</big> <i> - Orientadora</i></small>
Que tipo de informações?

2022-08-21 17:42 UTC, vcnovaes commented on module2/src/index.js
> +    '3': 'Alto - cerca de 38 cm',
Entendo, mas essa altura fixa é de quanto exatamente? 5 cm?

2022-08-21 17:56 UTC, aalmds commented on module2/src/index.js
> +    '3': 'Alto - cerca de 38 cm',
Sim, colocamos "cerca" porque não dá pra afirmar onde estaria do momento que passa daquele sensor até antes de chegar no outro.

2022-08-21 18:39 UTC, vcnovaes commented on module2/src/equipe.html
> +              <small> <big>Edna Barros</big> <i> - Orientadora</i></small>
Algo tipo o q rebecca falou.  De por professora,  etc.  Podia ser o cargo dela na ufpe que é professora/pesquisadora adjunta tipo oq ta no site do cin.

2022-08-21 18:46 UTC, vcnovaes commented on module2/src/index.js
> +    '3': 'Alto - cerca de 38 cm',
Acho q poderiamos usar uma variavel tipo sensorDefaultHeight e printar ela + a diferença  da altura do sensor no cano,  tlgd? 
Tipo

```js
let mesuDefaultHeight = 5


// e la no map da altura vc teria
 
... 
 '1':`baixo -  cerca de ${mesuDefaultHeight + alturaDoSensor1noPrototipo}`

```

2022-08-21 22:01 UTC, acrucha requested changes

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.html
> +              <a class="nav-link" href="./index.html">Mapeamento dos sensores</a>
Acho que seria legal, mas no caso a gente precisaria colocar um título na página do mapa pra ficar explicativo

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.html
> +                <th class="tbHeader">Dado</th>
```suggestion
                <th class="tbHeader">Dado->Nível</th>
```

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.html
> +            <button class="button button1" onclick="showTable()">History</button>
```suggestion
            <button class="button button1" onclick="showTable()">Histórico</button>
```

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.html
> +            <button class="button button1" onclick="showTable()">History</button>
Tua sugestão seria colocar onde?

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.js
> +    '0': 'Seco',
```suggestion
    '0': 'Muito Baixo - abaixo de 5 cm',

```

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.js
> +    '1': 'Muito baixo - cerca de 5 cm',
```suggestion
    '1': 'Baixo - cerca de 5 cm',

```

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.js
> +    '2': 'Baixo - cerca de 22 cm',
```suggestion
    '2': 'Médio - cerca de 15 cm',

```

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.js
> +    '3': 'Alto - cerca de 38 cm',
```suggestion
    '3': 'Alto - cerca de 30 cm',

```

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.js
> +    '4': 'Muito alto -  cerca de 48 cm',
```suggestion
    '4': 'Muito alto -  cerca de 45 cm',

```

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.js
> +    '4': 'Muito alto -  cerca de 48 cm',
Tipo, por padrão, como é um protótipo, a gente pode assumir que ele  tem uma altura fixa inicial de 5cm do chão. Aí já sugeri edições pra casar com isso.

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.js
> +    statusElement.innerText = 'Ok'
Acho que como não tem nada em capslock, fica meio estranho com OK maiúsculo

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.js
> +    '3': 'Alto - cerca de 38 cm',
Acho que como é um protótipo a gente pode deixar essa default fixa de 5cm mesmo

2022-08-21 22:01 UTC, acrucha commented on module2/src/index.html
> +<!doctype html>
Tu acha que precisa mesmo colocar a logo do CIn? Não é bem algo do CIn, aí acho que não precisaria

2022-08-21 22:37 UTC, mluisass commented on module2/src/equipe.html
> +              <p><br><img src = "../img/Vitoria.jpeg" width="100" > </img>
Onde isso seria colocado? Ao lado do nome da graduação? Ou indicaríamos de outra forma que somos todos da UFPE?

2022-08-21 22:56 UTC, becca-ls commented on module2/src/index.js
> +    '4': 'Muito alto -  cerca de 48 cm',
mas não tem um padrão? Vini deu uma sugestão tb

2022-08-21 22:58 UTC, vcnovaes commented on module2/src/index.js
> +    '3': 'Alto - cerca de 38 cm',
ok

2022-08-21 22:59 UTC, vcnovaes commented on module2/src/equipe.html
> +              <p><br><img src = "../img/Vitoria.jpeg" width="100" > </img>
Acho que poderia ser ao lado de cada nome, fazer algo tipo: 

Vinicius Novaes - Graduando em Eng.Computação, UFPE

2022-08-21 22:59 UTC, becca-ls commented on module2/src/index.html
> +            <button class="button button1" onclick="showTable()">History</button>
Na minha opinião ou volta a tabela pra baixo ou bota o botão lá perto da tabela, de alguma forma que fique esteticamente ok. Eu gostava antes, mas acho que a maioria preferiu do lado, ent o botão deveria ir junto. Outra possibilidade seria aquele botão sumir qnd aparecesse a tabela e o botão de "não mostrar o histórico ficasse lá perto da tabela", mas acho que fica mt complexo, n sei

2022-08-21 23:01 UTC, becca-ls commented on module2/src/index.html
> +<!doctype html>
Não é obrigatório não, só achei que seria legal ter alguma referência de onde a gente é. Mas não é fundamental não, só sugestão mesmo, é o de menos.

2022-08-21 23:21 UTC, becca-ls commented on module2/src/index.html
> +              <a class="nav-link" href="./index.html">Mapeamento dos sensores</a>
Ou pode colocar mapa, mapeamento, algo para não ficar uma frase que acaba sendo longo demais para um ícone

2022-08-23 14:28 UTC, becca-ls approved these changes

2022-08-23 14:32 UTC, vcnovaes approved these changes
Lgtm

2022-08-23 14:32 UTC, vcnovaes commented on module2/src/index.html
> +              <a class="nav-link" href="./index.html">Mapeamento dos sensores</a>
hm, eu n sei, acho que sim. Talvez fosse legal adicionar um titulo

2022-08-23 14:32 UTC, vcnovaes commented on module2/src/index.html
> +                <th class="tbHeader">Dado</th>
Veeee acho que me expresse errado kkk eu quis dizer substituir Dado para Nível

2022-08-23 14:34 UTC, acrucha approved these changes

2022-08-28 05:18 UTC, merged